// Commodity family mapping
export type CommodityFamily = 'all' | 'fruits' | 'vegetables' | 'roots_shoots' | 'commercial_crops';

export const commodityFamilyLabels: Record<CommodityFamily, string> = {
  all: 'All',
  fruits: 'Fruits',
  vegetables: 'Vegetables',
  roots_shoots: 'Roots & Shoots',
  commercial_crops: 'Commercial Crops',
};

// Mapping of commodities to their families (case-insensitive matching)
const commodityMapping: Record<string, CommodityFamily> = {
  // Fruits
  'apple': 'fruits',
  'banana': 'fruits',
  'mango': 'fruits',
  'orange': 'fruits',
  'grapes': 'fruits',
  'grape': 'fruits',
  'papaya': 'fruits',
  'watermelon': 'fruits',
  'muskmelon': 'fruits',
  'pomegranate': 'fruits',
  'guava': 'fruits',
  'pineapple': 'fruits',
  'sapota': 'fruits',
  'chikoo': 'fruits',
  'custard apple': 'fruits',
  'jack fruit': 'fruits',
  'jackfruit': 'fruits',
  'lemon': 'fruits',
  'lime': 'fruits',
  'sweet lime': 'fruits',
  'mosambi': 'fruits',
  'mousambi': 'fruits',
  'kinnow': 'fruits',
  'fig': 'fruits',
  'strawberry': 'fruits',
  'litchi': 'fruits',
  'cherry': 'fruits',
  'plum': 'fruits',
  'pear': 'fruits',
  'peach': 'fruits',
  'apricot': 'fruits',
  'dates': 'fruits',
  'coconut': 'fruits',
  'tender coconut': 'fruits',
  'amla': 'fruits',
  'ber': 'fruits',
  'jamun': 'fruits',
  'sitaphal': 'fruits',
  'wood apple': 'fruits',
  'bael': 'fruits',
  'rambutan': 'fruits',
  'dragon fruit': 'fruits',
  'kiwi': 'fruits',
  'avocado': 'fruits',
  
  // Vegetables
  'tomato': 'vegetables',
  'onion': 'vegetables',
  'potato': 'vegetables',
  'brinjal': 'vegetables',
  'eggplant': 'vegetables',
  'cabbage': 'vegetables',
  'cauliflower': 'vegetables',
  'capsicum': 'vegetables',
  'bell pepper': 'vegetables',
  'chilli': 'vegetables',
  'green chilli': 'vegetables',
  'red chilli': 'vegetables',
  'lady finger': 'vegetables',
  'bhindi': 'vegetables',
  'okra': 'vegetables',
  'beans': 'vegetables',
  'french beans': 'vegetables',
  'peas': 'vegetables',
  'green peas': 'vegetables',
  'spinach': 'vegetables',
  'palak': 'vegetables',
  'methi': 'vegetables',
  'fenugreek': 'vegetables',
  'coriander': 'vegetables',
  'mint': 'vegetables',
  'curry leaves': 'vegetables',
  'bitter gourd': 'vegetables',
  'karela': 'vegetables',
  'bottle gourd': 'vegetables',
  'lauki': 'vegetables',
  'ridge gourd': 'vegetables',
  'snake gourd': 'vegetables',
  'ash gourd': 'vegetables',
  'pointed gourd': 'vegetables',
  'parwal': 'vegetables',
  'ivy gourd': 'vegetables',
  'tinda': 'vegetables',
  'pumpkin': 'vegetables',
  'cucumber': 'vegetables',
  'drumstick': 'vegetables',
  'moringa': 'vegetables',
  'amaranth': 'vegetables',
  'cluster beans': 'vegetables',
  'gwar': 'vegetables',
  'broad beans': 'vegetables',
  'lettuce': 'vegetables',
  'celery': 'vegetables',
  'broccoli': 'vegetables',
  'zucchini': 'vegetables',
  'mushroom': 'vegetables',
  'corn': 'vegetables',
  'sweet corn': 'vegetables',
  'baby corn': 'vegetables',
  
  // Roots & Shoots
  'carrot': 'roots_shoots',
  'radish': 'roots_shoots',
  'beetroot': 'roots_shoots',
  'turnip': 'roots_shoots',
  'sweet potato': 'roots_shoots',
  'tapioca': 'roots_shoots',
  'yam': 'roots_shoots',
  'elephant foot yam': 'roots_shoots',
  'suran': 'roots_shoots',
  'colocasia': 'roots_shoots',
  'arbi': 'roots_shoots',
  'ginger': 'roots_shoots',
  'turmeric': 'roots_shoots',
  'garlic': 'roots_shoots',
  'spring onion': 'roots_shoots',
  'leek': 'roots_shoots',
  'bamboo shoot': 'roots_shoots',
  'lotus stem': 'roots_shoots',
  'water chestnut': 'roots_shoots',
  'asparagus': 'roots_shoots',
  
  // Commercial Crops
  'rice': 'commercial_crops',
  'paddy': 'commercial_crops',
  'wheat': 'commercial_crops',
  'maize': 'commercial_crops',
  'jowar': 'commercial_crops',
  'sorghum': 'commercial_crops',
  'bajra': 'commercial_crops',
  'millet': 'commercial_crops',
  'ragi': 'commercial_crops',
  'barley': 'commercial_crops',
  'oats': 'commercial_crops',
  'groundnut': 'commercial_crops',
  'peanut': 'commercial_crops',
  'soyabean': 'commercial_crops',
  'soybean': 'commercial_crops',
  'sunflower': 'commercial_crops',
  'mustard': 'commercial_crops',
  'sesame': 'commercial_crops',
  'til': 'commercial_crops',
  'castor': 'commercial_crops',
  'cotton': 'commercial_crops',
  'jute': 'commercial_crops',
  'sugarcane': 'commercial_crops',
  'tobacco': 'commercial_crops',
  'tea': 'commercial_crops',
  'coffee': 'commercial_crops',
  'rubber': 'commercial_crops',
  'cardamom': 'commercial_crops',
  'pepper': 'commercial_crops',
  'black pepper': 'commercial_crops',
  'clove': 'commercial_crops',
  'cinnamon': 'commercial_crops',
  'nutmeg': 'commercial_crops',
  'arecanut': 'commercial_crops',
  'betel nut': 'commercial_crops',
  'cashew': 'commercial_crops',
  'cashewnut': 'commercial_crops',
  'arhar': 'commercial_crops',
  'tur': 'commercial_crops',
  'pigeon pea': 'commercial_crops',
  'chana': 'commercial_crops',
  'gram': 'commercial_crops',
  'chickpea': 'commercial_crops',
  'moong': 'commercial_crops',
  'mung': 'commercial_crops',
  'urad': 'commercial_crops',
  'black gram': 'commercial_crops',
  'masoor': 'commercial_crops',
  'lentil': 'commercial_crops',
  'rajma': 'commercial_crops',
  'kidney bean': 'commercial_crops',
  'copra': 'commercial_crops',
  'dry coconut': 'commercial_crops',
  'jaggery': 'commercial_crops',
  'gur': 'commercial_crops',
};

export function getCommodityFamily(commodity: string): CommodityFamily {
  const normalizedCommodity = commodity.toLowerCase().trim();
  
  // Direct match
  if (commodityMapping[normalizedCommodity]) {
    return commodityMapping[normalizedCommodity];
  }
  
  // Partial match - check if commodity contains any key
  for (const [key, family] of Object.entries(commodityMapping)) {
    if (normalizedCommodity.includes(key) || key.includes(normalizedCommodity)) {
      return family;
    }
  }
  
  // Default to commercial crops for unknown items
  return 'commercial_crops';
}

export function filterByFamily(commodities: string[], family: CommodityFamily): string[] {
  if (family === 'all') {
    return commodities;
  }
  return commodities.filter(c => getCommodityFamily(c) === family);
}
